import { useState } from 'react';
import { WeavifyElement } from "@/types/weavify";

export interface ComponentTemplate {
  type: string;
  width: number;
  height: number;
  styles: any;
  content?: string;
}

export const componentTemplates: Record<string, ComponentTemplate> = {
  // Layout & Structure
  section: {
    type: 'section',
    width: 1200,
    height: 500,
    styles: {
      backgroundColor: '#f8fafc',
      borderRadius: 12,
      padding: 60,
      display: 'flex',
      flexDirection: 'column',
      justifyContent: 'center',
      alignItems: 'center',
      gap: 20,
    },
  },
  container: {
    type: 'container',
    width: 800,
    height: 400,
    styles: {
      backgroundColor: '#ffffff',
      border: '2px solid #e2e8f0',
      borderRadius: 16,
      padding: 40,
      boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.1)',
    },
  },
  flex: {
    type: 'flex',
    width: 900,
    height: 300,
    styles: {
      backgroundColor: '#ffffff',
      border: '1px solid #e2e8f0',
      borderRadius: 12,
      padding: 24,
      display: 'flex',
      gap: 16,
      alignItems: 'stretch',
    },
  },
  grid: {
    type: 'grid',
    width: 900,
    height: 400,
    styles: {
      backgroundColor: '#ffffff',
      border: '1px solid #e2e8f0',
      borderRadius: 12,
      padding: 24,
      display: 'grid',
      gridTemplateColumns: 'repeat(3, 1fr)',
      gap: 16,
    },
  },
  columns: {
    type: 'columns',
    width: 1000,
    height: 350,
    styles: {
      display: 'grid',
      gridTemplateColumns: 'repeat(2, 1fr)',
      gap: 32,
      padding: 24,
    },
  },
  header: {
    type: 'header',
    width: 1200,
    height: 80,
    styles: {
      backgroundColor: '#ffffff',
      borderBottom: '2px solid #e2e8f0',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'space-between',
      padding: '0 48px',
      boxShadow: '0 1px 3px rgba(0, 0, 0, 0.1)',
    },
  },
  footer: {
    type: 'footer',
    width: 1200,
    height: 200,
    styles: {
      backgroundColor: '#1e293b',
      color: '#ffffff',
      padding: 48,
      display: 'flex',
      flexDirection: 'column',
      justifyContent: 'center',
      alignItems: 'center',
      gap: 16,
    },
  },
  hero: {
    type: 'hero',
    width: 1200,
    height: 600,
    styles: {
      backgroundColor: '#3b82f6',
      backgroundImage: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
      color: '#ffffff',
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      justifyContent: 'center',
      padding: 80,
      textAlign: 'center',
      gap: 24,
    },
    content: 'Welcome to Our Platform',
  },
  sidebar: {
    type: 'sidebar',
    width: 280,
    height: 600,
    styles: {
      backgroundColor: '#f1f5f9',
      borderRight: '2px solid #e2e8f0',
      padding: 24,
      display: 'flex',
      flexDirection: 'column',
      gap: 12,
    },
  },

  // Navigation
  navbar: {
    type: 'navbar',
    width: 1200,
    height: 70,
    styles: {
      backgroundColor: '#1e293b',
      color: '#ffffff',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'space-between',
      padding: '0 48px',
      boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.1)',
    },
    content: 'My Website',
  },
  menu: {
    type: 'menu',
    width: 250,
    height: 400,
    styles: {
      backgroundColor: '#ffffff',
      border: '1px solid #e2e8f0',
      borderRadius: 8,
      padding: 8,
      boxShadow: '0 10px 15px -3px rgba(0, 0, 0, 0.1)',
    },
  },
  breadcrumb: {
    type: 'breadcrumb',
    width: 400,
    height: 40,
    styles: {
      display: 'flex',
      alignItems: 'center',
      gap: 8,
      fontSize: 14,
      color: '#64748b',
    },
    content: 'Home / Products / Category',
  },

  // Content
  text: {
    type: 'text',
    width: 400,
    height: 50,
    styles: {
      fontSize: 16,
      color: '#334155',
      lineHeight: 1.6,
      padding: 12,
    },
    content: 'Edit this text by clicking on it',
  },
  heading: {
    type: 'heading',
    width: 600,
    height: 80,
    styles: {
      fontSize: 48,
      fontWeight: '700',
      color: '#0f172a',
      lineHeight: 1.2,
      padding: 12,
    },
    content: 'Heading Text',
  },
  paragraph: {
    type: 'paragraph',
    width: 700,
    height: 120,
    styles: {
      fontSize: 16,
      color: '#475569',
      lineHeight: 1.75,
      padding: 16,
    },
    content: 'This is a paragraph. You can write multiple lines of text here. Click to edit and customize the content to match your needs.',
  },
  link: {
    type: 'link',
    width: 150,
    height: 40,
    styles: {
      fontSize: 16,
      color: '#3b82f6',
      textDecoration: 'underline',
      cursor: 'pointer',
      display: 'flex',
      alignItems: 'center',
      padding: 8,
    },
    content: 'Click here',
  },
  list: {
    type: 'list',
    width: 400,
    height: 200,
    styles: {
      backgroundColor: '#ffffff',
      padding: 24,
      fontSize: 14,
      lineHeight: 2,
    },
    content: '• List item 1\n• List item 2\n• List item 3\n• List item 4',
  },
  table: {
    type: 'table',
    width: 800,
    height: 300,
    styles: {
      backgroundColor: '#ffffff',
      border: '1px solid #e2e8f0',
      borderRadius: 8,
      overflow: 'hidden',
    },
  },
  code: {
    type: 'code',
    width: 600,
    height: 200,
    styles: {
      backgroundColor: '#1e293b',
      color: '#e2e8f0',
      fontFamily: 'monospace',
      fontSize: 14,
      padding: 24,
      borderRadius: 8,
      overflow: 'auto',
    },
    content: 'const greeting = "Hello World";\nconsole.log(greeting);',
  },
  quote: {
    type: 'quote',
    width: 600,
    height: 150,
    styles: {
      backgroundColor: '#f8fafc',
      borderLeft: '4px solid #3b82f6',
      padding: 24,
      fontSize: 18,
      fontStyle: 'italic',
      color: '#475569',
    },
    content: '"This is an inspiring quote that captures attention."',
  },

  // Media
  image: {
    type: 'image',
    width: 400,
    height: 300,
    styles: {
      backgroundColor: '#e2e8f0',
      borderRadius: 12,
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      fontSize: 14,
      color: '#64748b',
      objectFit: 'cover',
    },
    content: '🖼️ Image Placeholder',
  },
  video: {
    type: 'video',
    width: 640,
    height: 360,
    styles: {
      backgroundColor: '#000000',
      borderRadius: 12,
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      color: '#ffffff',
    },
    content: '▶️ Video Player',
  },
  audio: {
    type: 'audio',
    width: 400,
    height: 80,
    styles: {
      backgroundColor: '#f1f5f9',
      border: '1px solid #e2e8f0',
      borderRadius: 8,
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      padding: 16,
    },
    content: '🎵 Audio Player',
  },
  icon: {
    type: 'icon',
    width: 60,
    height: 60,
    styles: {
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      fontSize: 32,
    },
    content: '⭐',
  },
  
  // New Advanced Templates
  featuregrid: {
    type: 'grid',
    width: 1200,
    height: 500,
    styles: {
      display: 'grid',
      gridTemplateColumns: 'repeat(3, 1fr)',
      gap: 32,
      padding: 48,
      backgroundColor: '#ffffff',
    },
  },
  pricingcard: {
    type: 'card',
    width: 350,
    height: 500,
    styles: {
      backgroundColor: '#ffffff',
      border: '2px solid #e2e8f0',
      borderRadius: 16,
      padding: 32,
      display: 'flex',
      flexDirection: 'column',
      gap: 20,
      boxShadow: '0 10px 25px -5px rgba(0, 0, 0, 0.1)',
      transition: 'transform 0.3s',
    },
    content: 'Pricing Plan',
  },
  ctasection: {
    type: 'section',
    width: 1200,
    height: 400,
    styles: {
      backgroundColor: '#3b82f6',
      backgroundImage: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
      color: '#ffffff',
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      justifyContent: 'center',
      padding: 80,
      borderRadius: 24,
      gap: 24,
    },
    content: 'Ready to get started?',
  },
  statscard: {
    type: 'card',
    width: 280,
    height: 180,
    styles: {
      backgroundColor: '#f8fafc',
      border: '1px solid #e2e8f0',
      borderRadius: 12,
      padding: 24,
      display: 'flex',
      flexDirection: 'column',
      gap: 12,
    },
    content: '1,234',
  },
  videohero: {
    type: 'section',
    width: 1200,
    height: 700,
    styles: {
      backgroundColor: '#000000',
      position: 'relative',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      overflow: 'hidden',
    },
    content: 'Video Background Hero',
  },
  testimonialcard: {
    type: 'card',
    width: 400,
    height: 250,
    styles: {
      backgroundColor: '#ffffff',
      border: '1px solid #e2e8f0',
      borderRadius: 16,
      padding: 28,
      display: 'flex',
      flexDirection: 'column',
      gap: 16,
      boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.1)',
    },
    content: '"Amazing product! Highly recommended."',
  },
  teamgrid: {
    type: 'grid',
    width: 1200,
    height: 600,
    styles: {
      display: 'grid',
      gridTemplateColumns: 'repeat(4, 1fr)',
      gap: 24,
      padding: 48,
      backgroundColor: '#f8fafc',
    },
  },
  gallery: {
    type: 'gallery',
    width: 900,
    height: 500,
    styles: {
      display: 'grid',
      gridTemplateColumns: 'repeat(3, 1fr)',
      gap: 16,
      padding: 24,
      backgroundColor: '#f8fafc',
      borderRadius: 12,
    },
  },
  carousel: {
    type: 'carousel',
    width: 800,
    height: 400,
    styles: {
      backgroundColor: '#f1f5f9',
      borderRadius: 16,
      overflow: 'hidden',
      position: 'relative',
    },
  },

  // Forms
  input: {
    type: 'input',
    width: 350,
    height: 50,
    styles: {
      backgroundColor: '#ffffff',
      border: '2px solid #e2e8f0',
      borderRadius: 8,
      padding: 14,
      fontSize: 16,
      outline: 'none',
    },
    content: 'Type here...',
  },
  textarea: {
    type: 'textarea',
    width: 400,
    height: 150,
    styles: {
      backgroundColor: '#ffffff',
      border: '2px solid #e2e8f0',
      borderRadius: 8,
      padding: 14,
      fontSize: 16,
      resize: 'vertical',
    },
    content: 'Enter your message...',
  },
  select: {
    type: 'select',
    width: 250,
    height: 50,
    styles: {
      backgroundColor: '#ffffff',
      border: '2px solid #e2e8f0',
      borderRadius: 8,
      padding: 14,
      fontSize: 16,
      cursor: 'pointer',
    },
    content: 'Select an option ▼',
  },
  checkbox: {
    type: 'checkbox',
    width: 200,
    height: 40,
    styles: {
      display: 'flex',
      alignItems: 'center',
      gap: 12,
      fontSize: 16,
      cursor: 'pointer',
    },
    content: '☐ Checkbox label',
  },
  radio: {
    type: 'radio',
    width: 200,
    height: 40,
    styles: {
      display: 'flex',
      alignItems: 'center',
      gap: 12,
      fontSize: 16,
      cursor: 'pointer',
    },
    content: '○ Radio option',
  },
  button: {
    type: 'button',
    width: 180,
    height: 50,
    styles: {
      backgroundColor: '#3b82f6',
      color: '#ffffff',
      borderRadius: 10,
      fontSize: 16,
      fontWeight: '600',
      display: 'flex',
      justifyContent: 'center',
      alignItems: 'center',
      cursor: 'pointer',
      border: 'none',
      boxShadow: '0 4px 6px -1px rgba(59, 130, 246, 0.4)',
      transition: 'all 0.2s',
    },
    content: 'Click Me',
  },
  form: {
    type: 'form',
    width: 500,
    height: 450,
    styles: {
      backgroundColor: '#ffffff',
      border: '1px solid #e2e8f0',
      borderRadius: 16,
      padding: 40,
      boxShadow: '0 10px 15px -3px rgba(0, 0, 0, 0.1)',
    },
  },
  slider: {
    type: 'slider',
    width: 300,
    height: 40,
    styles: {
      padding: 12,
    },
  },
  toggle: {
    type: 'toggle',
    width: 80,
    height: 40,
    styles: {
      backgroundColor: '#e2e8f0',
      borderRadius: 20,
      padding: 4,
      cursor: 'pointer',
    },
  },
  loginform: {
    type: 'loginform',
    width: 400,
    height: 450,
    styles: {
      backgroundColor: '#ffffff',
      border: '1px solid #e2e8f0',
      borderRadius: 16,
      padding: 48,
      boxShadow: '0 20px 25px -5px rgba(0, 0, 0, 0.1)',
      display: 'flex',
      flexDirection: 'column',
      gap: 24,
    },
  },
  signupform: {
    type: 'signupform',
    width: 450,
    height: 550,
    styles: {
      backgroundColor: '#ffffff',
      border: '1px solid #e2e8f0',
      borderRadius: 16,
      padding: 48,
      boxShadow: '0 20px 25px -5px rgba(0, 0, 0, 0.1)',
      display: 'flex',
      flexDirection: 'column',
      gap: 20,
    },
  },
  contactform: {
    type: 'contactform',
    width: 500,
    height: 500,
    styles: {
      backgroundColor: '#ffffff',
      border: '1px solid #e2e8f0',
      borderRadius: 16,
      padding: 40,
      boxShadow: '0 10px 15px -3px rgba(0, 0, 0, 0.1)',
      display: 'flex',
      flexDirection: 'column',
      gap: 20,
    },
  },

  // Components
  card: {
    type: 'card',
    width: 350,
    height: 450,
    styles: {
      backgroundColor: '#ffffff',
      border: '1px solid #e2e8f0',
      borderRadius: 16,
      overflow: 'hidden',
      boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.1)',
      transition: 'all 0.3s',
    },
  },
  modal: {
    type: 'modal',
    width: 500,
    height: 350,
    styles: {
      backgroundColor: '#ffffff',
      borderRadius: 16,
      padding: 32,
      boxShadow: '0 20px 25px -5px rgba(0, 0, 0, 0.3)',
      position: 'relative',
    },
  },
  accordion: {
    type: 'accordion',
    width: 600,
    height: 250,
    styles: {
      backgroundColor: '#ffffff',
      border: '1px solid #e2e8f0',
      borderRadius: 12,
      overflow: 'hidden',
    },
  },
  tabs: {
    type: 'tabs',
    width: 700,
    height: 400,
    styles: {
      backgroundColor: '#ffffff',
      border: '1px solid #e2e8f0',
      borderRadius: 12,
      overflow: 'hidden',
    },
  },
  tooltip: {
    type: 'tooltip',
    width: 200,
    height: 70,
    styles: {
      backgroundColor: '#1e293b',
      color: '#ffffff',
      borderRadius: 8,
      padding: 12,
      fontSize: 14,
      boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.2)',
    },
    content: 'Tooltip text',
  },
  toast: {
    type: 'toast',
    width: 350,
    height: 80,
    styles: {
      backgroundColor: '#10b981',
      color: '#ffffff',
      borderRadius: 12,
      padding: 16,
      boxShadow: '0 10px 15px -3px rgba(0, 0, 0, 0.2)',
      display: 'flex',
      alignItems: 'center',
      gap: 12,
    },
    content: '✓ Action completed successfully!',
  },
  badge: {
    type: 'badge',
    width: 80,
    height: 30,
    styles: {
      backgroundColor: '#3b82f6',
      color: '#ffffff',
      borderRadius: 16,
      padding: '6px 12px',
      fontSize: 12,
      fontWeight: '600',
      display: 'inline-flex',
      alignItems: 'center',
      justifyContent: 'center',
    },
    content: 'New',
  },
  progress: {
    type: 'progress',
    width: 400,
    height: 30,
    styles: {
      backgroundColor: '#e2e8f0',
      borderRadius: 16,
      overflow: 'hidden',
    },
  },
  spinner: {
    type: 'spinner',
    width: 60,
    height: 60,
    styles: {
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      fontSize: 32,
    },
    content: '⟳',
  },
  avatar: {
    type: 'avatar',
    width: 80,
    height: 80,
    styles: {
      backgroundColor: '#3b82f6',
      color: '#ffffff',
      borderRadius: '50%',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      fontSize: 32,
      fontWeight: '600',
    },
    content: 'JD',
  },
  divider: {
    type: 'divider',
    width: 800,
    height: 2,
    styles: {
      backgroundColor: '#e2e8f0',
    },
  },

  // E-commerce
  productcard: {
    type: 'productcard',
    width: 320,
    height: 480,
    styles: {
      backgroundColor: '#ffffff',
      border: '1px solid #e2e8f0',
      borderRadius: 16,
      overflow: 'hidden',
      boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.1)',
    },
  },
  pricetable: {
    type: 'pricetable',
    width: 350,
    height: 550,
    styles: {
      backgroundColor: '#ffffff',
      border: '2px solid #e2e8f0',
      borderRadius: 16,
      padding: 40,
      boxShadow: '0 10px 15px -3px rgba(0, 0, 0, 0.1)',
    },
  },
  testimonial: {
    type: 'testimonial',
    width: 450,
    height: 280,
    styles: {
      backgroundColor: '#f8fafc',
      border: '1px solid #e2e8f0',
      borderRadius: 16,
      padding: 32,
      display: 'flex',
      flexDirection: 'column',
      gap: 20,
    },
  },
  countdown: {
    type: 'countdown',
    width: 500,
    height: 150,
    styles: {
      backgroundColor: '#1e293b',
      color: '#ffffff',
      borderRadius: 16,
      padding: 32,
      display: 'flex',
      justifyContent: 'center',
      alignItems: 'center',
      fontSize: 48,
      fontWeight: '700',
    },
    content: '00:00:00',
  },
  chatwidget: {
    type: 'chatwidget',
    width: 350,
    height: 500,
    styles: {
      backgroundColor: '#ffffff',
      border: '1px solid #e2e8f0',
      borderRadius: 16,
      boxShadow: '0 20px 25px -5px rgba(0, 0, 0, 0.2)',
      overflow: 'hidden',
    },
  },
  socialmedia: {
    type: 'socialmedia',
    width: 300,
    height: 60,
    styles: {
      display: 'flex',
      gap: 16,
      alignItems: 'center',
      justifyContent: 'center',
    },
  },
  newsletter: {
    type: 'newsletter',
    width: 500,
    height: 200,
    styles: {
      backgroundColor: '#3b82f6',
      color: '#ffffff',
      borderRadius: 16,
      padding: 40,
      display: 'flex',
      flexDirection: 'column',
      gap: 16,
      justifyContent: 'center',
      alignItems: 'center',
    },
  },

  // Advanced
  chart: {
    type: 'chart',
    width: 600,
    height: 400,
    styles: {
      backgroundColor: '#ffffff',
      border: '1px solid #e2e8f0',
      borderRadius: 12,
      padding: 24,
    },
  },
  map: {
    type: 'map',
    width: 800,
    height: 500,
    styles: {
      backgroundColor: '#e2e8f0',
      borderRadius: 12,
      overflow: 'hidden',
    },
  },
  calendar: {
    type: 'calendar',
    width: 350,
    height: 400,
    styles: {
      backgroundColor: '#ffffff',
      border: '1px solid #e2e8f0',
      borderRadius: 12,
      padding: 16,
    },
  },
  datepicker: {
    type: 'datepicker',
    width: 300,
    height: 50,
    styles: {
      backgroundColor: '#ffffff',
      border: '2px solid #e2e8f0',
      borderRadius: 8,
      padding: 14,
      fontSize: 16,
      cursor: 'pointer',
    },
    content: '📅 Select date',
  },
  search: {
    type: 'search',
    width: 400,
    height: 50,
    styles: {
      backgroundColor: '#ffffff',
      border: '2px solid #e2e8f0',
      borderRadius: 25,
      padding: '0 20px',
      fontSize: 16,
      display: 'flex',
      alignItems: 'center',
    },
    content: '🔍 Search...',
  },
  pagination: {
    type: 'pagination',
    width: 350,
    height: 50,
    styles: {
      display: 'flex',
      gap: 8,
      alignItems: 'center',
      justifyContent: 'center',
    },
  },
  iframe: {
    type: 'iframe',
    width: 800,
    height: 600,
    styles: {
      border: '1px solid #e2e8f0',
      borderRadius: 12,
      backgroundColor: '#f8fafc',
    },
  },
  embed: {
    type: 'embed',
    width: 600,
    height: 400,
    styles: {
      backgroundColor: '#f1f5f9',
      border: '1px solid #e2e8f0',
      borderRadius: 12,
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
    },
    content: 'Embed Content',
  },
  canvas: {
    type: 'canvas',
    width: 800,
    height: 600,
    styles: {
      backgroundColor: '#ffffff',
      border: '2px solid #e2e8f0',
      borderRadius: 12,
    },
  },
  svg: {
    type: 'svg',
    width: 300,
    height: 300,
    styles: {
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
    },
  },
  faq: {
    type: 'faq',
    width: 700,
    height: 400,
    styles: {
      backgroundColor: '#ffffff',
      border: '1px solid #e2e8f0',
      borderRadius: 12,
      padding: 32,
    },
  },
  stats: {
    type: 'stats',
    width: 900,
    height: 200,
    styles: {
      display: 'grid',
      gridTemplateColumns: 'repeat(3, 1fr)',
      gap: 24,
      padding: 24,
    },
  },
  timeline: {
    type: 'timeline',
    width: 700,
    height: 500,
    styles: {
      backgroundColor: '#ffffff',
      padding: 40,
      position: 'relative',
    },
  },
  pricing: {
    type: 'pricing',
    width: 1000,
    height: 600,
    styles: {
      display: 'grid',
      gridTemplateColumns: 'repeat(3, 1fr)',
      gap: 32,
      padding: 40,
    },
  },
  team: {
    type: 'team',
    width: 1000,
    height: 500,
    styles: {
      display: 'grid',
      gridTemplateColumns: 'repeat(4, 1fr)',
      gap: 24,
      padding: 40,
    },
  },
  blogpost: {
    type: 'blogpost',
    width: 800,
    height: 600,
    styles: {
      backgroundColor: '#ffffff',
      borderRadius: 16,
      padding: 48,
      maxWidth: 800,
    },
  },
  portfolio: {
    type: 'portfolio',
    width: 400,
    height: 500,
    styles: {
      backgroundColor: '#ffffff',
      border: '1px solid #e2e8f0',
      borderRadius: 16,
      overflow: 'hidden',
      boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.1)',
    },
  },
};


